/**
 * Copyright since 2026 Mifos Initiative
 *
 * <p>This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy
 * of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.apache.fineract.selfservice.account.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the {@code data} payload inside the SAME_BANK transfer confirmation response. The
 * structure intentionally mirrors the response envelope returned by the external core-banking
 * switch so that mobile / web clients can use a single deserialization path for every transfer
 * channel (SAME_BANK, PIN, SINPE_MOVIL).
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SameBankTransferResponseData {

  /** Commission / fee amount charged for this transfer. */
  private BigDecimal commissionAmount;

  /** ISO-4217 currency code of the commission (e.g. "CRC", "USD"). */
  private String commissionCurrency;

  /** Arbitrary key/value pairs for receipt and reconciliation use. */
  private SameBankTransferCustomData customData;

  /** ISO-4217 currency code of the debited account. */
  private String debitCurrencyCode;

  /** Net amount debited from the source account. */
  private BigDecimal debitedAmount;

  /** Exchange rate applied. 0 for same-currency, same-bank transfers. */
  private BigDecimal exchangeRate;

  /** Unique operation identifier (UUID) generated for this transfer execution. */
  private String operationId;

  /** Timestamp when the transfer was processed by the core. */
  private String processingDate;

  /** Timestamp when the transfer was initially registered / received. */
  private String registrationDate;

  /** Rejection reason. Empty string when the transfer is successful. */
  private String rejectDescription;
  
  /** Channel Ref Number. Empty string when the transfer is successful. */
  private String channelRefNumber;

  /**
   * Internal reference number generated by the platform. Format: {@code YYYYMMDD} + {@code officeId
   * (5 digits)} + {@code resourceId (12 digits)}.
   */
  private String internalRefNumber;

  /** Human-readable state of the transfer (e.g. "Completaded", "Rejected"). */
  private String stateDescription;

  /** Whether the transfer completed successfully. */
  private boolean successful;

  private int stateCode;
  
  private Integer rejectCode;
  
  private String sinpeRefNumber;

}
