name: Publish package to the Mifos Artifactory and GitHub Packages
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up Java for publishing to Mifos Artifactory
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: central
          server-username: ARTIFACTORY_USERNAME
          server-password: ARTIFACTORY_PASSWORD
      - name: Publish to the Mifos Artifactory
        run: mvn -DskipITs --batch-mode deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
