name: Publish package to the Mifos Artifactory and GitHub Packages
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Java for publishing to Mifos Artifactory
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: central
          server-username: ARTIFACTORY_USERNAME
          server-password: ARTIFACTORY_PASSWORD
      - name: Publish to the Mifos Artifactory
        run: mvn -DskipITs --batch-mode deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
